---
apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZHdrcDM2c2d3  # Updated value (base64 encoded)
  CLOUDINARY_KEY: NDUzNzYzOTY4NzY3OTU5NTk2  # Updated value (base64 encoded)
  CLOUDINARY_SECRET: NXhxTExaZ1B0S3dRaGVaUEdzb3pR  # Updated value (base64 encoded)
  MAPBOX_TOKEN: c2suZXlKMUlja2Z3YldWNklpd2liVlJqWlhabGFXNXBkR0Y1WkM1b2IyNWpaRzlyYVc0bWNteHhlcmh0dzBxcGQyanNmb2YyYXo1b24ifQ==  # Updated value (base64 encoded)
  DB_URL: bW9uZ29kYjptb25nb2RiLm5ldDovL2RhdGFiYXNl  # Updated value (base64 encoded)
  SECRET: cmFodWw=  # Updated value (base64 encoded)

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelp-camp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelp-camp
  template:
    metadata:
      labels:
        app: yelp-camp
    spec:
      containers:
        - name: yelp-camp-container
          image: adijaiswal/campa:latest
          ports:
            - containerPort: 3000
          env:
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_KEY
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_KEY
            - name: CLOUDINARY_SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_SECRET
            - name: MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: MAPBOX_TOKEN
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: DB_URL
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: SECRET

---
apiVersion: v1
kind: Service
metadata:
  name: yelp-camp-service
spec:
  selector:
    app: yelp-camp
  ports:
    - protocol: TCP
      port: 3000   # External port exposed as 3000
      targetPort: 3000  # Internal port of the container
  type: LoadBalancer

