
name: CI

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest  # Use GitHub-hosted Ubuntu runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: Rahul7600/3-Tier-Full-Stack
          token: ${{ secrets.YOUR_GITHUB_TOKEN }}
          path: /home/ec2-user/3-Tier-Full-Stack  # Set the checkout path

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: |
            cd /home/ec2-user/3-Tier-Full-Stack
            # Perform deployment tasks in the correct directory

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'  # Adjust Node.js version as needed

      - name: Install dependencies
        working-directory: /home/ec2-user/3-Tier-Full-Stack
        run: npm install

      - name: Run unit tests
        working-directory: /home/ec2-user/3-Tier-Full-Stack
        run: npm test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build & tag
        working-directory: /home/ec2-user/3-Tier-Full-Stack
        run: |
          docker build -t rahul7600/camp:latest .
          docker push rahul7600/camp:latest

      - name: Run Docker container
        working-directory: /home/ec2-user/3-Tier-Full-Stack
        run: |
          docker run -d --name camp -p 3000:3000 rahul7600/camp:latest

      - name: Open Web Client Directory
        working-directory: /home/ec2-user/3-Tier-Full-Stack/src/webclient
        run: ls -la










