
name: CI

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest  # Use GitHub-hosted Ubuntu runner

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: |
            cd /home/ec2-user/3-Tier-Full-Stack

      - name: Set Git Config Locally
        run: |
          git config user.name "rahul"
          git config user.email "rahul@gmail.com"
        working-directory: /home/ec2-user/3-Tier-Full-Stack  # Ensure Git commands run in the correct directory

      # Additional steps for Node.js, npm install, tests, Docker setup, etc.



