name: Build and Push Docker Image to Docker Hub

# Trigger the workflow on pushes to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx for building the image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub using credentials stored in GitHub Secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build the Docker image and tag it with the commit SHA and 'latest' tag
      - name: Build and tag Docker image
        run: |
          docker build -t rahul7600/my-app:latest -t rahul7600/my-app:${{ github.sha }} .

      # Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push rahul7600/my-app:latest
          docker push rahul7600/my-app:${{ github.sha }}

